name: Continuous Deploy

on: 
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu@latest
    name: Build & Deploy
    steps:
      - name: Checkout    
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build

      # 利用action把build好的文件上传到服务器路径下,需要确认此目录已在服务端创建
      - name: Deploy File to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'root'   #ssh user name
          server: '${{ vars.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './build/*' 
          remote_path: '/www/wwwroot/www.jungeshuo.asia/build'